name: artifactory

on:
 push:
  tags:
    - v[0-9]+.[0-9]+.[0-9]+

jobs:
  artifactory:
    env:
      JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_SECRET_1 }}
    runs-on: ubuntu-latest
    steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.3
    - name: Update Rubygems
      run: gem update --system 3.1.0
    - name: Get latest tag
      run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        ref: ${{ env.RELEASE_VERSION }}
    - name: Push to artifactory
      uses: jfrog/setup-jfrog-cli@v1
      run: |
        # Ping the server
        jfrog rt ping
