name: release

on:
 push:
  tags:
    - v[0-9]+.[0-9]+.[0-9]+

jobs:
  release:
    env:
      BLACKSMITH_FORGE_USERNAME: ${{ secrets.FORGE_USERNAME }}
      BLACKSMITH_FORGE_PASSWORD: ${{ secrets.FORGE_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.3
    - name: Update Rubygems
      run: gem update --system 3.1.0
    - name: Get latest tag
      run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        ref: ${{ env.RELEASE_VERSION }}
    - name: Release
      run: | 
        bundle install --with release
        bundle exec rake module:build
        bundle exec rake module:push
